CRUD_CBV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crud_system.urls')),
]

crud_system/urls.py
from django.urls import path
from . import views

app_name = 'crud_system'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('list/', views.SchoolListView.as_view(), name='list'),
    path('list/<int:pk>/', views.SchoolDetailView.as_view(), name='detail'),

    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.SchoolDeleteView.as_view(), name='delete'),


]

crud_system/models.py
from django.db import models
from django.urls import reverse_lazy

# Create your models here.

class School(models.Model):
    school_type = [
        ('boys_school', 'Boys School'),
        ('girls_school', 'Girls School'),
        ('coeducation_school', 'Codecuation School'),
    ]

    school_name = models.CharField(max_length=120)
    school_type = models.CharField(max_length=20, choices=school_type, default='coeducation_school')
    principal_name = models.CharField(max_length=100)
    location = models.CharField(max_length=200)

    def get_absolute_url(self):
        return reverse_lazy('detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.school_name



class Student(models.Model):
    student_name = models.CharField(max_length=150)
    roll_number = models.PositiveIntegerField(null=True)
    school_name = models.ForeignKey(School, on_delete=models.CASCADE, related_name = 'student')

    def __str__(self):
        return self.student_name

crud_system/views.py
from django.shortcuts import render
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from .models import School, Student



# Create your views here.

class IndexView(TemplateView):
    template_name = 'crud_system/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['inserted_data'] = 'This data is inserted from views'
        return context


class SchoolListView(ListView):
    context_object_name = 'school_list'
    model = School


class SchoolDetailView(DetailView):
    context_object_name = 'detail_con'
    model = School

    template_name = 'crud_system/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('school_name', 'school_type', 'principal_name', 'location')
    model = School

    success_url = reverse_lazy('crud_system:list')


class SchoolUpdateView(UpdateView):
    fields = ('school_name', 'school_type', 'principal_name', 'location')
    model = School


class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy('crud_system:list')

crud_system/templates/crud_system/base.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>
    {% block title_block %}

    {% endblock %}
  </title>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>

<body>
  <!--Navbar-->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!-- Navbar brand -->
    <a class="navbar-brand" href="#">Navbar</a>
    <!-- Collapse button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Collapsible content -->
    <div class="collapse navbar-collapse" id="basicExampleNav">
      <!-- Links -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'crud_system:index' %}">Home<span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crud_system:list' %}">School List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'crud_system:create' %}">Creat School</a>
        </li>
      </ul>
      <!-- Links -->
      <form class="form-inline">
        <div class="md-form my-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        </div>
      </form>
    </div>
    <!-- Collapsible content -->
  </nav>
  <!--/.Navbar-->

  {% block body_block %}

  {% endblock %}

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

crud_system/templates/crud_system/index.html
{% extends "crud_system/base.html" %}

{% block title_block %}
  Home
{% endblock %}

{% block body_block %}
  <div class="container">
    <h1>Home Page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>


    <h3>{{ inserted_data }}</h3>
  </div>

{% endblock %}

crud_system/templates/crud_system/school_confirm_delete.html
{% extends "crud_system/base.html" %}

{% block title_block %}
  Confirm Delete
{% endblock %}

{% block body_block %}
  <div class="container">
    <h3>Are you sure, want to delete!!! {{school.school_name}}</h3>
    <form class="form" method="POST">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" name="" value="Delete">
      <a class="btn btn-danger" href="{% url 'crud_system:detail' pk=school.pk %}">Cancel</a>
    </form>
  </div>

{% endblock %}

crud_system/templates/crud_system/school_detail.html
{% extends "crud_system/base.html" %}

{% block title_block %}
  School Detail
{% endblock %}

{% block body_block %}
<div class="container">
  <div class="jumbotron container">
    <h3 class="">School Detail:</h3>
    <h5>Name: {{detail_con.school_name }}</h5>
    <h5>Principal: {{detail_con.principal_name }}</h5>
    <h5>Location: {{detail_con.location }}</h5>
    <br><br>
  </div>
  <div class="container">
    <a class="btn btn-info" href="{% url 'crud_system:update' pk=detail_con.pk %}">Update School</a>
    <a class="btn btn-info" href="{% url 'crud_system:delete' pk=detail_con.pk %}">Delete School</a>
  </div>
  <br><br>

  <div class="jumbotron container">
    <h3 class="">Sudents:</h3>
      <ol>
        {% for each_student in detail_con.student.all  %}
          <li> <h5>Name: {{each_student.student_name}}, Roll: {{each_student.roll_number}}</h5> </li>
        {% endfor %}
      </ol>
  </div>


</div>




{% endblock %}

crud_system/templates/crud_system/school_form.html
{% extends "crud_system/base.html" %}

{% block title_block %}
  School Form
{% endblock %}

{% block body_block %}
  {% if not form.instance.pk %}
    <h3>Create School</h3>
  {% else %}
    <h3>Update School</h3>
  {% endif %}

  <div class="container">
    <form class="form"  method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input class="btn btn-success" type="submit" name="" value="Create School">
    </form>
  </div>
{% endblock %}

crud_system/templates/crud_system/school_list.html
{% extends "crud_system/base.html" %}

{% block title_block %}
  School list
{% endblock %}

{% block body_block %}
  <div class="jumbotron">
    <h1 class="display-3">List of Schools</h1>
    <ol>
      {% for school in school_list %}
        <li> <a href="{{school.id}}"> {{school.school_name}}</a></li>
      {% endfor %}
    </ol>
  </div>
{% endblock %}